name: Meteor CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # 👈 Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Meteor 1.8.0
        run: curl curl https://install.meteor.com/?release=1.8.2 | sh

      - name: Install NPM Packages
        run: meteor npm install

      - name: Build Meteor App (Server Bundle)
        run: |
          meteor build ./build-output --architecture os.linux.x86_64
          ls -lh ./build-output
      
      - name: Upload Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: meteor-bundle
          path: build-output/*.tar.gz
